version: '3'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/jupiter-git:cached
      - /usr/jupiter-git/node_modules
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - PORT=8000
